# Generated by Django 5.1.6 on 2025-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_address_alter_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_thumbnail',
            name='thumbnail_img',
            field=models.ImageField(default='', null=True, upload_to='img/room_img'),
        ),
    ]
