# Generated by Django 5.1.6 on 2025-02-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_thumbnail_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_specification',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='room_thumbnail',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='rooms.room'),
        ),
    ]
