# Generated by Django 5.1.6 on 2025-04-28 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 11, 30, 16, 467128, tzinfo=datetime.timezone.utc)),
        ),
    ]
