# Generated by Django 5.1.6 on 2025-03-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
