# Generated by Django 5.1.6 on 2025-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='img/default_user/default_user.webp', null=True, upload_to='img/user_img'),
        ),
    ]
