# Generated by Django 5.1.6 on 2025-03-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_rejected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='pending', max_length=10),
        ),
    ]
