# Generated by Django 5.1.6 on 2025-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('rejected', 'Rejected'), ('hold', 'Hold'), ('cancel', 'Cancel')], default='pending', max_length=10),
        ),
    ]
